#job:
#  script:
#    - echo "Um exemplo de sessao de script."
#  after_script:
#    - echo "Execute este comando depois de um conjunto completo de `script`."

job:
  script:
    - echo "Um exemplo de executar pipeline quando muda um arquivo."
  only:
    refs:
      - branches
    changes:
      - teste.txt