#job:
  # use special keywords
#  when: manual
#  script:
#    - echo " Executa somente manual."

#job:
#  script:
#    - echo "Um exemplo de sessao de script."
#  after_script:
#    - echo "Execute este comando depois de um conjunto completo de `script`."

#job:
#  script:
#    - echo "Um exemplo de executar pipeline quando muda um arquivo."
#  only:
#    changes:
#      - teste.txt
#      - docker/scripts/*
#      - more_scripts/*.{rb,py,sh}

job:
  script: echo "Executar somente quando alterar arquivos com extensão .md"
  except:
    changes:
      - "*.md"

#job:
#  script:
#    - echo "Mostrando variaveis do GitLab"
#    - export

#job:
#  script: echo "Pipeline executa quando for na branch main e com usuário claudiosilva"
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main" && $GITLAB_USER_LOGIN == "claudiosilva"'
#      when: manual
#    - if: '$CI_COMMIT_BRANCH == "feature"'
#      when: never
#      allow_failure: true

#job:
  # use special keywords
#  only:
#    - tags
#  script:
#    - echo " Este Job executa somente com tag."
#  when: manual

end-to-end:
  script: echo "Executa exceto mensagem de commit skip-tests"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/