stages:
  - e1
  - e2
  - e3

Etapa1:
  stage: e1
  when: on_success
  script:
    - dsfdsfds echo "Etapa 1"

Etapa2:
  stage: e2
  when: on_failure
  script:
    - echo "Falha na Etapa 1"

Etapa3:
  stage: e3
  when: always
  script:
    - echo "Sempre será executado"
