build_a:
  image: alpine
  script:
    - echo "Executando um build"
    - sleep 10
  tags:
    - docker

test_a:
  needs: [build_a]
  script:
    - docker run -dit --name teste ubuntu
  tags:
    - shell
  
