build_a:
  image: alpine
  script:
    - echo "Executando um build"
    - sleep 15
  tags:
    - docker

test_a:
  needs: [build_a]
  image: ubuntu
  script:
    - echo "Executando um build"
  tags:
    - docker
  
