#job:
  # use special keywords
#  when: manual
#  script:
#    - echo " Executa somente manual."

#job:
#  script:
#    - echo "Um exemplo de sessao de script."
#  after_script:
#    - echo "Execute este comando depois de um conjunto completo de `script`."

#job:
#  script:
#    - echo "Um exemplo de executar pipeline quando muda um arquivo."
#  only:
#    changes:
#      - teste.txt
#      - docker/scripts/*
#        - "*.md"
#      - more_scripts/*.{rb,py,sh}

#job:
#  script:
#    - echo "Mostrando variaveis do GitLab"
#    - export

#job:
#  script: echo "Pipeline executa quando for na branch main e com usuário claudiosilva"
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main" && $GITLAB_USER_LOGIN == "claudiosilva"'
#      when: manual
#    - if: '$CI_COMMIT_BRANCH == "feature"'
#      when: never
#      allow_failure: true

#job:
#  only:
#    - tags
#  script:
#    - echo " Este Job executa somente com tag."
#  when: manual

#end-to-end:
#  script: echo "Executa exceto mensagem de commit skip-tests"
#  except:
#    variables:
#      - $CI_COMMIT_MESSAGE =~ /skip-tests/

#Executar com cronometro:
#  stage: deploy
#  script: echo 'Execucao em 1 minuto...'
#  when: delayed
#  start_in: 1 minutes #5 seconds, 30 minutes, 1 day, 1 week

#job:
#  parallel: 3
#  script:
#    - echo "3 trabalhos trabalho paralelo"

#job:
#  only:
#    - tags
#  when: manual
#  script:
#    - echo " Este Job executa com gatilho de tag."
# Utilizado para gatilho com curl
#curl -X POST \
#     --fail \
#     -F token=c450ddc1e103178a5f6c1d0cd9d6e9 \
#     -F "ref=0.0.1" \
#     https://gitlab.com/api/v4/projects/34316608/trigger/pipeline

#job:
#  timeout: 1m
#  script:
#    - sleep 20
#    - echo "executa com timeout para o stage com maximo de 1 minuto"

#job1:
#  only:
#    variables:
#      - $GATILHO == "valor"
#  script:
#    - echo "Executando job por uma variavel == valor"
# Utilizado como teste para gatilho com curl
#curl -X POST \
#     --fail \
#     -F token=c450ddc1e103178a5f6c1d0cd9d6e9 \
#     -F "ref=main" \
#     -F "variables[GATILHO]=valor" \
#     https://gitlab.com/api/v4/projects/34316608/trigger/pipeline


#image: alpine
#build_a:
#  script:
#    - echo "Este job compila somente."
#test_a:
#  needs: [build_a]
#  script:
#    - echo "este job precisa do build_a."
#deploy_a:
#  needs: [test_a]
#  script:
#    - echo "este job precisa do test_a."

#variables:
#  GLOBAL_VAR: global
#job1:
#  script:
#    - echo " Apresenta declaração de variavel $GLOBAL_VAR"
#job2:
#  variables:
#    LOCAL_VAR: local
#  script:
#    - echo Apresenta declaração de variavel $GLOBAL_VAR"
#    - echo Apresenta declaração de variavel $LOCAL_VAR"

#job:
#  script:
#    - echo "Este trabalho executa quando solicita mesclagem"
#  only:
#    - merge_requests


job:
  stage: test
  script:
    - echo "$CI_JOB_STAGE"
    - echo "$TEST"
    - echo "$GREETING"
    - cat "$GREETING"


#Fontes
# Gatilho de pipeline com Curl - https://docs.gitlab.com/ee/ci/triggers/#use-curl
# - https://docs.gitlab.com/ee/ci/jobs/job_control.html
# Runner Docker - https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#register-a-runner-that-uses-the-docker-executor
