stages:
  - ola

Ola mundo:
  image: ubuntu:21.04
  stage:
    ola
  when: manual
  script:
    - pwd
    - id
    - ls -l
    - hostname
    - apt-get update && apt-get install -y git
    - git branch -va
