#job:
#  script:
#    - echo "Um exemplo de sessao de script."
#  after_script:
#    - echo "Execute este comando depois de um conjunto completo de `script`."

#job:
#  script:
#    - echo "Um exemplo de executar pipeline quando muda um arquivo."
#  only:
#    changes:
#      - teste.txt
#      - docker/scripts/*
#      - more_scripts/*.{rb,py,sh}

job:
  script:
    - echo "Mostrando variaveis do GitLab"
    - export
    